name: "Test"
on:
  pull_request:
  push:
jobs:
  get-flake-checks:
    runs-on: ubuntu-latest
    outputs:
      flake-checks: "${{ steps.set-outputs.outputs.checks }}"
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@8887e596b4ee1134dae06b98d573bd674693f47c
      - uses: DeterminateSystems/magic-nix-cache-action@87b14cf437d03d37989d87f0fa5ce4f5dc1a330b
      - run: >
          nix flake show --json 
          | jq -rc '.checks["x86_64-linux"] 
          | keys' >> "flake-checks"
      - id: set-outputs
        run: echo "checks=$(cat flake-checks)" >> "$GITHUB_OUTPUT"

  build:
    runs-on: ubuntu-latest
    outputs:
      flake-checks: "${{ steps.set-outputs.outputs.checks }}"
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@8887e596b4ee1134dae06b98d573bd674693f47c
      - uses: DeterminateSystems/magic-nix-cache-action@87b14cf437d03d37989d87f0fa5ce4f5dc1a330b
      - run: nix build

  flake-checks:
    runs-on: ubuntu-latest
    needs: [ flake-checks, build ]
    strategy: 
      matrix:
        check: ${{ fromJSON(needs.get-flake-checks.outputs.flake-checks) }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@8887e596b4ee1134dae06b98d573bd674693f47c
      - uses: DeterminateSystems/magic-nix-cache-action@87b14cf437d03d37989d87f0fa5ce4f5dc1a330b
      - run: nix build -L ".#checks.$check"
        env:
          check: "${{ matrix.check }}"
